name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Type YES to confirm destroying infrastructure'
        required: true
        default: 'NO'

jobs:
  destroy:
    if: github.event.inputs.destroy == 'YES'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: terraform/envs/dev
        run: terraform destroy -auto-approve
