name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Type YES to confirm destroying infrastructure'
        required: true
        default: 'NO'

jobs:
  destroy:
    if: github.event.inputs.destroy == 'YES'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: terraform/envs/dev
        run: terraform destroy -auto-approve
